# Generated by Django 5.1.1 on 2024-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEM_MED', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationschedule',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='time_to_take',
            field=models.CharField(choices=[('ตอนเช้า', 'ตอนเช้า'), ('ตอนกลางวัน', 'ตอนกลางวัน'), ('ตอนเย็น', 'ตอนเย็น'), ('ตอนกลางคืน', 'ตอนกลางคืน')], max_length=10),
        ),
    ]
