# Generated by Django 5.1.1 on 2024-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEM_MED', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
