# Generated by Django 5.1.1 on 2024-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEM_MED', '0002_remove_medicationschedule_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationschedule',
            name='is_eaten',
            field=models.BooleanField(default=False),
        ),
    ]
