# Generated by Django 5.1.2 on 2024-10-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEM_MED', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationschedule',
            name='is_eaten',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
