# Generated by Django 5.1.2 on 2024-10-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEM_MED', '0003_alter_medicationschedule_is_eaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationschedule',
            name='is_eaten',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
