# Generated by Django 5.1.1 on 2024-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEM_MED', '0004_alter_medicationschedule_is_eaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='is_read',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
