# Generated by Django 5.1.2 on 2024-11-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEM_MED', '0005_remove_doctorappointment_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MEM_MED.doctor'),
        ),
    ]
