# Generated by Django 5.1.1 on 2024-11-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MEM_MED', '0005_doctorappointment_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='is_read',
        ),
    ]
