pipeline {
    agent any

    environment {
        DOCKER_IMAGE    = 'sundance02/mem_med:latest'
        REMOTE_HOST     = 'fame050647@34.143.237.227'
        SSH_CREDENTIALS = 'ssh-prod_instance'
        DOCKER_CREDENTIALS = credentials('dockerhub')
    }

    stages {
        
        stage('Start Jenkins') {
            steps {
                sh 'echo Start Jenkins............'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('./Devtool_Cloud_project') {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }   
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    sh 'echo $DOCKER_CREDENTIALS_PSW | docker login --username $DOCKER_CREDENTIALS_USR --password-stdin'
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USER')]) {
                    sh 'echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USER --password-stdin'
                }
            }
        }

        stage('SSH to Remote Server') {
            steps {
                script {
                    // ใช้ SSH เข้าสู่เซิร์ฟเวอร์
                    sshagent([SSH_CREDENTIALS]) {
                        sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'echo Connected to remote server'"
                    }
                }
            }
        }

        stage('Copy Docker Compose to Remote') {
            steps {
                sshagent([SSH_CREDENTIALS]) {
                    // คัดลอกไฟล์ docker-compose.yml ไปยังเซิร์ฟเวอร์ remote
                    sh "scp -o StrictHostKeyChecking=no ./docker-compose.yml $REMOTE_HOST:/path/to/remote/directory"
                }
            }
        }

        stage('Run Docker Compose on Remote Server') {
            steps {
                sshagent([SSH_CREDENTIALS]) {
                    // Pull Docker image บน remote server และใช้ docker-compose ขึ้น container
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker-compose pull'"
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker-compose down || true'"  // หยุดการทำงานของ container เดิม
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker-compose up -d'"  // รัน container ใหม่
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker-compose ps'"  // ตรวจสอบสถานะ container
                }
            }
        }
    }

    post {
        always {
            sh 'docker logout'
        }
    }
}
